version: 0.2

phases:
  install:
    commands:
      - pip install -r requirements.txt
  build:
    commands:
      - echo "Build complete. Ready to deploy."
artifacts:
  files:
    - app.py
    - requirements.txt
